stages:
    - format

cmake-check:
    stage: format
    allow_failure: true
    image: mfila/alpine-format
    script:
    - cmake-format --version
    - cmake-format -i $(find . -name "*.cmake")
    - cmake-format -i $(find . -name "CMakeLists.txt")
    - git diff --exit-code
        
clang-check:
    stage: format
    allow_failure: true
    image: mfila/alpine-format
    script:
    - clang-format --version
    - clang-format -i $(find COREdcs -name "*.cpp")
    - clang-format -i $(find COREdcs -name "*.h")
    - clang-format -i $(find ELITPCdcs -name "*.cpp")
    - clang-format -i $(find ELITPCdcs -name "*.h")
    - git diff --exit-code