stages:
    - build

image: open62541/open62541
before_script:
    - apt-get update
    - apt-get install --yes cmake

format:
    stage: build
    script:
        - cmake -H. -Bbuild
        - cmake --build build --target format
