image: mfila/open62541
stages:
    - format
    - build
    - deploy
    - lint
    
cmake-check:
    stage: format
    allow_failure: true
    script:
    - cmake-format --version
    - cmake-format -i $(find . -name "*.cmake")
    - cmake-format -i $(find . -name "CMakeLists.txt")
    - git diff --exit-code
        
clang-check:
    stage: format
    allow_failure: true
    script:
    - clang-format-8 --version
    - clang-format-8 -i $(find COREdcs -name "*.cpp")
    - clang-format-8 -i $(find COREdcs -name "*.h")
    - clang-format-8 -i $(find ELITPCdcs -name "*.cpp")
    - clang-format-8 -i $(find ELITPCdcs -name "*.h")
    - git diff --exit-code

#build_ssh:
#  stage: build
#  tags:
#  - ssh
#  script:
#    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/dcs-install
#    - cmake --build build
#  artifacts:
#     paths:
#     - build

staging_ssh:
  stage: deploy
  tags:
  - ssh
  script:
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/dcs-install
    - cmake --build build --target install
  artifacts:
     paths:
     - build

#build_release:
#  stage: build
#  script:
#    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
#    - cmake --build build 
#  artifacts:
#    paths:
#      - build
      
build_debug:
  stage: build
  script:
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_EXE_LINKER_FLAGS="-coverage"
    - cmake --build build 
#  artifacts:
#    paths:
#      - build

export_commands:
 stage: build
 script:
    - rm -rf build
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=clang++-8
 artifacts:
    paths:
      - build


lint_clang_tidy:
  stage: lint
  allow_failure: true
  dependencies:
    - export_commands
  script:
    - cd build
    - run-clang-tidy-8

lint_iwyu:
  stage: lint
  allow_failure: true
  dependencies:
    - export_commands
  script:
    - cd build
    - iwyu_tool.py -p .

lint_cppcheck:
  allow_failure: true
  stage: lint
  dependencies:
    - export_commands
  script:
    - cd build
    - cppcheck --error-exitcode=1 -i $PWD/../deps -i $PWD/../test ..
    
