#!/bin/bash

# Debian-based
if [[ -f /etc/lsb-release ]]; then

    # Remove or purge
    if [[ "$1" != "upgrade" ]]; then

        if command -v systemctl &>/dev/null; then
            systemctl disable dcs-server
            rm -f /usr/lib/systemd/system/dcs-server.service
        fi
    fi
fi
